name = "azblob"

[namespace.service]

[namespace.service.new]
required = ["credential", "endpoint"]
optional = ["default_service_pairs", "http_client_options"]

[namespace.storage]
implement = ["appender"]

[namespace.storage.new]
required = ["name"]
optional = ["default_storage_pairs", "pair_policy", "work_dir"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size", "encryption_key", "encryption_scope"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "access_tier", "encryption_key", "encryption_scope"]

[namespace.storage.op.create_append]
optional = ["encryption_key", "encryption_scope"]

[namespace.storage.op.write_append]
optional = ["encryption_key", "encryption_scope"]

[namespace.storage.op.stat]
optional = ["encryption_key", "encryption_scope"]

[pairs.access_tier]
type = "string"

[pairs.default_service_pairs]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[pairs.encryption_key]
type = "byte_array"
description = "is the customer's 32-byte AES-256 key"

[pairs.encryption_scope]
type = "string"
description = "Specifies the name of the encryption scope. See https://docs.microsoft.com/en-us/azure/storage/blobs/encryption-scope-overview for details."

[infos.object.meta.access-tier]
type = "string"

[infos.object.meta.encryption-key-sha256]
type = "string"

[infos.object.meta.encryption-scope]
type = "string"

[infos.object.meta.server-encrypted]
type = "bool"
