name = "azblob"

[namespace.service]

[namespace.service.new]
required = ["credential", "endpoint"]
optional = ["default_service_pairs", "http_client_options", "pair_policy"]

[namespace.storage.new]
required = ["name"]
optional = ["default_storage_pairs", "work_dir"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "access_tier"]

[pairs.access_tier]
type = "string"

[pairs.default_service_pairs]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[infos.object.meta.access-tier]
type = "string"